### ISSUE TITLE
Null safety not working without configuration.  choiceGrouped fails.

### ISSUE THREAD

**Issue by Bockos** [akbarpulatov/flutter_awesome_select#16] opened 2021-11-07 06:30 UTC
Hi,

Default selected value is now nullable and  SmartSelect<String>.multiple is not nullable. I'm not able to handle that, but I fixed this with doing like this.  SmartSelect<String?>.multiple. Because if I dont, by default it shows this error;

![image](https://user-images.githubusercontent.com/23163077/140634825-f7a2abbd-b6e5-47ba-968f-a3c5ef35e4cd.png)

Now the issue is fixed and it shows the modal by fixing those 2 lines too;
 List<String?> _car = []; 
    onChange: (selected) => setState(() => _car = selected!.value!),

All is fine, but they all not working with choiceGrouped.

![image](https://user-images.githubusercontent.com/23163077/140634886-12c0f06f-ed0c-41fa-b7e3-b76a8b3daf98.png)

**Comment by gongxh13** [comment] 2021-11-12 05:24
I also find this problem, and want to know when to merge this bug into newest version?

**Comment by absar** [comment] 2021-11-12 19:38
It's duplicate of https://github.com/akbarpulatov/flutter_awesome_select/issues/13

**Comment by vasilich6107** [comment] 2021-11-12 23:00
@Bockos @gongxh13 @absar 
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by Bockos** [comment] 2021-11-15 14:33
@vasilich6107  Thanks bro, its worked without null check.
Well done!

**Comment by akbarpulatov** [comment] 2021-11-21 11:49
Issue is fixed on 834321de79dbb2b61befcfa8ddd97c90d2569c55

**Closed** 2021-11-21 11:49 UTC
Labels: bug
