### ISSUE TITLE
A value of type 'Color?' can't be assigned to a variable of type 'Color'

### ISSUE THREAD

**Issue by MartimTSilva** [akbarpulatov/flutter_awesome_select#26] opened 2022-02-04 12:27 UTC
I can't import the package without getting errors.
I've migrated my project to null-safety, and now just by importing awesome_select package I get these errors.
![image](https://user-images.githubusercontent.com/43602260/152528730-d694a762-8db6-42be-8fca-5263344ba9de.png)

**Comment by FelipeSamuel** [comment] 2022-02-04 15:07
some problem

**Comment by explorova** [comment] 2022-02-04 23:45
same here

**Comment by SuperKMan** [comment] 2022-02-05 01:07
got the same error too.

**Comment by Saulmarti** [comment] 2022-02-05 11:32
I have de same error.
To resolve it i downgrade the version of Flutter, the problem is with the version 1.10 of Flutter.

**Comment by vasilich6107** [comment] 2022-02-06 06:09
> > 
> 
> 
> 
> I hit this error as soon as I upgraded to flutter 2.10.0.   My app is not yet using full null-safety, I suspect flutter 2.10 is forcing, or assuming, something along those lines by default.

Why not to migrate to null safety?

**Comment by explorova** [comment] 2022-02-06 15:54
Still waiting on map_controller
  
  
   
  
  
   
    On 02/06/2022 1:09 AM Vasiliy Ditsyak ***@***.***> wrote:
   
   
    
   
   
    
   
   
   
    
    I hit this error as soon as I upgraded to flutter 2.10.0. My app is not yet using full null-safety, I suspect flutter 2.10 is forcing, or assuming, something along those lines by default.
   
   Why not to migrate to null safety?

**Comment by WieFel** [comment] 2022-02-07 08:22
> I can't import the package without getting errors. I've migrated my project to null-safety, and now just by importing awesome_select package I get these errors. ![image](https://user-images.githubusercontent.com/43602260/152528730-d694a762-8db6-42be-8fca-5263344ba9de.png)

+1

**Comment by Dagmawi-Asfaw-CH** [comment] 2022-02-07 08:40
i had the same problem when i upgraded to flutter 2.10.  it was fixed when I downgraded to version 2.8.1 on stable channel.

**Comment by youannis-aziz** [comment] 2022-02-07 14:18
same problem after upgrading

**Comment by gelintonx** [comment] 2022-02-09 15:07
Same problem here

**Comment by oncleguigs** [comment] 2022-02-09 19:32
Same problem here

**Comment by triopu** [comment] 2022-02-11 10:52
I changed package to smart_select because of this issue

**Comment by deddybear** [comment] 2022-02-25 14:20
hi, someone can help newest update in this repository to pub.dev/packages ? please :(

**Comment by vasilich6107** [comment] 2022-03-01 10:16
@MartimTSilva @FelipeSamuel @explorova @SuperKMan @Saulmarti @WieFel @Dagmawi-Asfaw-CH @youannis-aziz @gelintonx @oncleguigs @powerhai @FelipeSamuel @deddybear 
Fixed in https://pub.dev/packages/flutter_awesome_select/versions/6.1.2-beta

**Comment by Mathys-Rituper** [comment] 2022-04-04 08:08
> change dependence for
> 
> awesome_select: git: url: https://github.com/Flutter-Fox/flutter_awesome_select.git ref: hotfix-5.1.0

Sorry for bothering with such a basic question (I'm a beginner with Flutter) but is it to be done in pubspec.yml or pubspec.lock ? I can't get it to work in neither of the files

**Comment by akbarpulatov** [comment] 2022-04-08 06:03
Fixed in #27

**Closed by akbarpulatov** 2022-04-08 06:03 UTC
